config/routes.rb
Pulsar::Application.routes.draw do
  resources :users
	resources :sessions, :only => [:new, :create, :destroy]

	root :to => 'pages#home'

	match '/signup',  :to => 'users#new'
	
	match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
	
  match '/contact', :to => 'pages#contact'
	match '/about',   :to => 'pages#about'
	match '/terms',   :to => 'pages#terms'
	match '/privacy', :to => 'pages#privacy'

end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :password
	attr_accessible :name, :email, :password, :password_confirmation

	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates :name,  :presence   => true,
										:length     => { :maximum => 50 }
										
	validates :email, :presence   => true,
										:format     => { :with => email_regex },
										:uniqueness => { :case_sensitive => false }
										
	validates :password, :presence => true,
											 :confirmation => true,
											 :length => { :within => (6..40) }
											 
	before_save :encrypt_password
	
	def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
	
	def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end
	
	def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

	private

		def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
	
	include SessionsHelper
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
		@title = "Home"
  end

  def contact
		@title = "Contact"
  end

  def about
		@title = "About"
  end

  def terms
		@title = "Terms"
  end

  def privacy
		@title = "Privacy"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
		@title = "Sign In"
  end
	
	def create
		user = User.authenticate(params[:session][:email],
                           params[:session][:password])
		if user.nil?
			flash.now[:error] = "Invalid email/password combination."
      @title = "Sign In"
      render 'new'
		else
			sign_in user
			redirect_to user
		end
	end
	
	def destroy
    sign_out
    redirect_to root_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
		@user = User.new
		@title = "Sign Up"
  end
	
	def show
		@user = User.find(params[:id])
		@title = @user.name
	end
	
	def create
    @user = User.new(params[:user])
    if @user.save
			sign_in @user
			flash.now[:success] = "Welcome!"
      render 'show'
    else
      @title = "Sign Up"
      render 'new'
    end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def title
		base_title = "Pulsar"
		if @title.nil?
			base_title
		else
			"#{base_title} | #{@title}"
		end
	end
	
	def logo
		image_tag("logo.png", :alt => "Pulsar Logo")
	end
	
	def left_sidebar
		case
			when @title == "Sign Up"
				render "users/new-left-sidebar"
			when @title == @user.name
				render "users/show-left-sidebar"
			when @title == "Home"
				render "pages/home-left-sidebar"
			when @title == "Sign In"
				render "sessions/new-left-sidebar"
		end
	end

end

app/helpers/pages_helper.rb
module PagesHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    self.current_user = user
  end
	
	def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end
	
	def current_user=(user)
    @current_user = user
  end
	
	def current_user
    @current_user ||= user_from_remember_token
  end
	
	def signed_in?
    !current_user.nil?
  end
	
	private

    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end

    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end

end

app/helpers/users_helper.rb
module UsersHelper

	def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => user.name,
                                            :class => 'gravatar',
                                            :gravatar => options)
  end

end

app/views/layouts/_footer.html.erb
<footer class = "span-24 last">
<hr>
  <nav>
      [ <%= link_to "About", about_path %> | 
      <%= link_to "Contact", contact_path %> | 
			&copy; 2011 |
			<%= link_to "Terms", terms_path %> | 
			<%= link_to "Privacy", privacy_path %> ]
  </nav>
	<!-- <%= debug(params) if Rails.env.development? %> -->
</footer>

app/views/layouts/_header.html.erb
<header class = "span-24 last">
	<div class = "span-6 box-left">&nbsp;</div>
	<div class = "span-12">
		<%= link_to logo, root_path %>
	</div>

	<nav class = "span-3 box-right">
		<% if signed_in? %>
			<%= current_user.name %> </br />
			<%= link_to "Profile", current_user %>
		<% else %>
			New User?<br />
			<%= link_to "Sign Up", signup_path %>
		<% end %>
	</nav>
	
	<nav class = "span-3 last box-right">
		<% if signed_in? %>
			<br />
			<%= link_to "Sign Out", signout_path, :method => :delete %>
		<% else %>
			Existing User?<br />
			<%= link_to "Sign In", signin_path %>
		<% end %>
	</nav>

	<div class = "span-6">&nbsp;</div>
	
	<div class = "span-12">
		<% flash.each do |key, value| %>
      <%= content_tag(:div, value, :class => "flash #{key}") %>
    <% end %>
	</div>
	
	<div class = "span-6 last">&nbsp;</div>
	
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->    
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
  </head>
	
  <body>
    <div class="container">
		
      <%= render 'layouts/header' %>
			
			<div class = "span-5 colborder">
				<%= left_sidebar %>
				&nbsp; <br /><br />
			</div>
			
      <div class="span-12">
        <%= yield %>
      </div>
			
			<div class = "span-6 last">
				&nbsp;
			</div>
			
			<%= render 'layouts/footer' %>
			
    </div>
  </body>
	
</html>

app/views/pages/_home-left-sidebar.html.erb
<h3>Home L-Sidebar</h3>

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at ante. Mauris eleifend, quam a vulputate dictum, massa quam dapibus leo, eget vulputate orci purus ut lorem. In fringilla mi in ligula. Pellentesque aliquam quam vel dolor. Nunc adipiscing. Sed quam odio, tempus ac, aliquam molestie, varius ac, tellus. Vestibulum ut nulla aliquam risus rutrum interdum. 

<br /><br />

Pellentesque lorem. Curabitur sit amet erat quis risus feugiat viverra. Pellentesque augue justo, sagittis et, lacinia at, venenatis non, arcu. Nunc nec libero. In cursus dictum risus. Etiam tristique nisl a nulla. Ut a orci. Curabitur dolor nunc, egestas at, accumsan at, malesuada nec, magna.

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Welcome to pulsar!</h1>
<p>
	A fast, powerful way to follow eSports.
	<br><br>
	<%= link_to "Sign Up Now!", signup_path, :class => "signup_button" %>
	<br>
	Already have an account? <%= link_to "Sign In", signin_path %>
</p>

app/views/pages/privacy.html.erb
<h1>Pages#privacy</h1>
<p>Find me in app/views/pages/privacy.html.erb</p>

app/views/pages/terms.html.erb
<h1>Pages#terms</h1>
<p>Find me in app/views/pages/terms.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> 
        need to be fixed in order to successfully sign up:</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_new-left-sidebar.html.erb
<h3>Signup L-Sidebar</h3>

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at ante. Mauris eleifend, quam a vulputate dictum, massa quam dapibus leo, eget vulputate orci purus ut lorem. In fringilla mi in ligula. Pellentesque aliquam quam vel dolor. Nunc adipiscing. Sed quam odio, tempus ac, aliquam molestie, varius ac, tellus. Vestibulum ut nulla aliquam risus rutrum interdum. 

<br /><br />

Pellentesque lorem. Curabitur sit amet erat quis risus feugiat viverra. Pellentesque augue justo, sagittis et, lacinia at, venenatis non, arcu. Nunc nec libero. In cursus dictum risus. Etiam tristique nisl a nulla. Ut a orci. Curabitur dolor nunc, egestas at, accumsan at, malesuada nec, magna.

app/views/users/_show-left-sidebar.html.erb
<h3>Users Show L-Sidebar</h3>

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at ante. Mauris eleifend, quam a vulputate dictum, massa quam dapibus leo, eget vulputate orci purus ut lorem. In fringilla mi in ligula. Pellentesque aliquam quam vel dolor. Nunc adipiscing. Sed quam odio, tempus ac, aliquam molestie, varius ac, tellus. Vestibulum ut nulla aliquam risus rutrum interdum. 

<br /><br />

Pellentesque lorem. Curabitur sit amet erat quis risus feugiat viverra. Pellentesque augue justo, sagittis et, lacinia at, venenatis non, arcu. Nunc nec libero. In cursus dictum risus. Etiam tristique nisl a nulla. Ut a orci. Curabitur dolor nunc, egestas at, accumsan at, malesuada nec, magna.

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for(@user) do |f| %>
<%= render 'shared/error_messages' %>
  <div class="field">
    <%= f.label :name, "Username" %><br>
    <%= f.text_field :name, :size => "26" %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email, :size => "26"  %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password, :size => "26"  %>  <font class = "small">Needs to be at least 6 characters long.</font>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Password Confirm" %><br>
    <%= f.password_field :password_confirmation, :size => "26"  %>  <font class = "small">Retype your password.</font>
  </div>
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

<br />

app/views/users/show.html.erb
<h1>
  <%= gravatar_for @user %>
  <%= @user.name %>
</h1>